name: CI/CD - Build & Deploy (backend)

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ghcr.io/ics-pa-2025/2025_proyecto3_back_claimflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            set -e

            APP_DIR=/home/${{ secrets.DROPLET_USER }}/2025_proyecto3_back_claimflow
            mkdir -p $APP_DIR

            cat > $APP_DIR/.env <<EOF
            MONGO_URI=mongodb://root:rootpassword@mongo:27017/claimflow?authSource=admin
            NODE_ENV=production
            PORT=3000
            EOF

            cd $APP_DIR

            docker pull ${{ env.IMAGE_NAME }}:latest
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
